### ISSUE TITLE
No module named plugin

### ISSUE THREAD

**Issue by Spielzeug** [fferri/v_repStubsGen#1]
Catkin build of vrep_ros_interface fails with:

Traceback (most recent call last):
  File "/home/rei/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 9, in <module>
    from parse import parse
  File "/home/rei/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/parse.py", line 2, in <module>
    import model
  File "/home/rei/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/model/__init__.py", line 4, in <module>
    from plugin import *
ModuleNotFoundError: No module named 'plugin'
make[2]: *** [CMakeFiles/v_repExtRosInterface.dir/build.make:62: generated/stubs.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/v_repExtRosInterface.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Which plugin is it?

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repStubsGen#1
